/**
 * LocalElectionsTable.tsx
 *
 * Displays a searchable, accessible table of state-specific election deadlines
 * and voter ID requirements sourced from the Gemini US civic fallback engine.
 *
 * When the Gemini API returns structured civicData, this component parses it
 * into a readable, filterable table for the user.
 */
import React from 'react';

/** Shape of civic data returned by the Gemini US fallback endpoint */
export interface USCivicData {
  registration_deadline?: string;
  voter_id_requirements?: string;
  early_voting_dates?: string;
  absentee_ballot_rules?: string;
  polling_hours?: string;
}

interface LocalElectionsTableProps {
  /** The location that was searched (used as table title) */
  location: string;
  /** Structured civic data from Gemini US fallback */
  civicData: USCivicData;
}

/**
 * Renders a structured table of voter deadlines and requirements.
 * Includes a search/filter input to help users find specific info.
 *
 * @example
 * <LocalElectionsTable location="Austin, TX" civicData={data} />
 */
export const LocalElectionsTable: React.FC<LocalElectionsTableProps> = ({
  location,
  civicData,
}) => {
  const [filter, setFilter] = React.useState('');

  const rows = [
    { label: 'Registration Deadline', value: civicData.registration_deadline, icon: '📋' },
    { label: 'Voter ID Requirements', value: civicData.voter_id_requirements, icon: '🪪' },
    { label: 'Early Voting Dates', value: civicData.early_voting_dates, icon: '📅' },
    { label: 'Absentee Ballot Rules', value: civicData.absentee_ballot_rules, icon: '✉️' },
    { label: 'Polling Hours', value: civicData.polling_hours, icon: '🕐' },
  ].filter((row) => row.value); // Only show rows with data

  const filteredRows = filter.trim()
    ? rows.filter(
        (row) =>
          row.label.toLowerCase().includes(filter.toLowerCase()) ||
          (row.value ?? '').toLowerCase().includes(filter.toLowerCase())
      )
    : rows;

  if (rows.length === 0) return null;

  return (
    <section
      className="local-elections-table"
      aria-label={`Election requirements for ${location}`}
    >
      <header className="local-elections-table__header">
        <h2 className="election-page__section-title">
          <span aria-hidden="true">🗳️</span> Local Election Requirements
          <span className="local-elections-table__ai-badge" aria-label="AI generated data">
            ✨ AI
          </span>
        </h2>
        <p className="local-elections-table__subtitle">
          Civic data for <strong>{location}</strong> — generated by Gemini AI
        </p>
      </header>

      <div className="local-elections-table__search-wrapper">
        <label htmlFor="table-filter" className="sr-only">
          Filter election requirements
        </label>
        <input
          id="table-filter"
          type="search"
          className="local-elections-table__search"
          placeholder="🔍  Filter requirements…"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          aria-label="Filter election requirements table"
          aria-controls="election-requirements-table"
        />
      </div>

      {filteredRows.length === 0 ? (
        <p className="local-elections-table__empty" role="status">
          No results matching "{filter}"
        </p>
      ) : (
        <table
          id="election-requirements-table"
          className="local-elections-table__table"
          aria-label={`Election requirements for ${location}`}
        >
          <thead>
            <tr>
              <th scope="col" className="local-elections-table__th">
                Requirement
              </th>
              <th scope="col" className="local-elections-table__th">
                Details
              </th>
            </tr>
          </thead>
          <tbody>
            {filteredRows.map((row) => (
              <tr key={row.label} className="local-elections-table__row">
                <td className="local-elections-table__label-cell">
                  <span aria-hidden="true" className="local-elections-table__icon">
                    {row.icon}
                  </span>
                  <strong>{row.label}</strong>
                </td>
                <td className="local-elections-table__value-cell">{row.value}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </section>
  );
};
