import { Router, Request, Response } from 'express';
import axios from 'axios';
import { validateAddress } from '../middleware/validate';
import { GoogleGenerativeAI } from '@google/generative-ai';

const router = Router();

/** Base URL for the Google Civic Information API */
const CIVIC_API_BASE = 'https://www.googleapis.com/civicinfo/v2';

/**
 * Typed request with the sanitized address attached by the validation middleware.
 */
type CivicRequest = Request & { sanitizedAddress: string };

// ── Geocoding Types ───────────────────────────────────────────────────────────

/** A single address component from the Google Geocoding API */
interface GeoAddressComponent {
  long_name: string;
  short_name: string;
  types: string[];
}

/** A single result entry from the Google Geocoding API */
interface GeoResult {
  address_components: GeoAddressComponent[];
  formatted_address: string;
  geometry: {
    location: { lat: number; lng: number };
  };
}

/** The full response from the Google Geocoding API */
interface GeoApiResponse {
  status: string;
  results: GeoResult[];
}

// ── India Election Data Types ─────────────────────────────────────────────────

/**
 * Structured election data generated by Gemini for an Indian constituency.
 * All fields are optional to tolerate model variability.
 */
interface IndiaElectionData {
  constituency?: string;
  state?: string;
  electionType?: string;
  expectedElectionYear?: string | number;
  voterRegistrationSteps?: string[];
  electionProcessSummary?: string;
  phases?: {
    authorization?: string;
    intelligence?: string;
    logistics?: string;
    execution?: string;
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Geocodes an address and returns the first result, or null if not found.
 * Uses the Google Maps Geocoding API.
 *
 * @param address - The address string to geocode
 * @param apiKey - Google Maps / Geocoding API key
 * @returns The first GeoResult, or null
 */
async function geocodeAddress(address: string, apiKey: string): Promise<GeoResult | null> {
  try {
    const url = `https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(address)}&key=${apiKey}`;
    const response = await fetch(url, { signal: AbortSignal.timeout(6_000) });
    if (!response.ok) return null;
    const data = await response.json() as GeoApiResponse;
    if (data.status !== 'OK' || data.results.length === 0) return null;
    return data.results[0];
  } catch {
    return null;
  }
}

/**
 * Checks whether a geocoding result is located in India by examining
 * the `country` address component for the short name "IN".
 *
 * @param result - A GeoResult from the Geocoding API
 * @returns true if the country code is "IN"
 */
function isInIndia(result: GeoResult): boolean {
  return result.address_components.some(
    (c) => c.types.includes('country') && c.short_name === 'IN'
  );
}

/**
 * Extracts a specific address component by type from a GeoResult.
 *
 * @param result - A GeoResult object
 * @param type - The component type to look for (e.g. 'locality')
 * @returns The long name of the matching component, or undefined
 */
function getComponent(result: GeoResult, type: string): string | undefined {
  return result.address_components.find((c) => c.types.includes(type))?.long_name;
}

/**
 * Builds the structured Gemini prompt for Indian constituency data.
 *
 * @param location - City or locality name
 * @param state - State name
 * @returns A Gemini prompt string
 */
function buildIndiaPrompt(location: string, state: string): string {
  return `You are an expert on the Indian electoral system and the Election Commission of India (ECI).

A voter is located in ${location}${state ? `, ${state}` : ''}, India.

Generate a JSON object with EXACTLY this structure — no extra text, markdown, or code fences:
{
  "constituency": "<name of the Lok Sabha or Vidhan Sabha constituency>",
  "state": "<state name>",
  "electionType": "<'Lok Sabha' or 'State Assembly (Vidhan Sabha)' — whichever is most imminent>",
  "expectedElectionYear": "<year as a string, e.g. '2029'>",
  "voterRegistrationSteps": [
    "<step 1>",
    "<step 2>",
    "<step 3>",
    "<step 4>"
  ],
  "electionProcessSummary": "<2-3 sentence summary of the Indian election process for this constituency>",
  "phases": {
    "authorization": "<description of voter ID and registration verification for this location>",
    "intelligence": "<description of how to research candidates and parties for this constituency>",
    "logistics": "<description of finding the polling booth, EVM use, and voting timeline>",
    "execution": "<description of how to cast a vote on election day in India>"
  }
}`;
}

/**
 * Calls the Gemini API to generate structured election data for an Indian location.
 * Strips any accidental markdown code fences from the model output.
 *
 * @param location - City or locality
 * @param state - State
 * @param geminiKey - GEMINI_API_KEY
 * @returns Parsed IndiaElectionData, or throws on parse failure
 */
async function fetchIndiaDataFromGemini(
  location: string,
  state: string,
  geminiKey: string
): Promise<IndiaElectionData> {
  const genAI = new GoogleGenerativeAI(geminiKey);
  const model = genAI.getGenerativeModel({ model: 'gemini-1.5-flash' });
  const prompt = buildIndiaPrompt(location, state);
  const result = await model.generateContent(prompt);
  const rawText = result.response.text().trim();

  // Strip accidental markdown code fences
  const jsonText = rawText
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim();

  return JSON.parse(jsonText) as IndiaElectionData;
}

// ── Route ─────────────────────────────────────────────────────────────────────

/**
 * GET /api/civic
 *
 * Smart address resolver with Indian constituency bypass:
 *
 * 1. Validates the incoming address (via validateAddress middleware).
 * 2. Attempts to geocode the address using the Google Maps Geocoding API.
 * 3. **If the geocoding result has country_code = "IN" (India)**:
 *    - Immediately bypasses the Google Civic Information API.
 *    - Calls Gemini 1.5 Flash to synthesise ECI-compliant election data.
 *    - Returns an `indiaFallback: true` response.
 * 4. Otherwise, proceeds with the standard US Civic Information API flow.
 *
 * @query address - The voter's address string (validated by middleware)
 * @returns CivicVoterInfo, fallback elections list, or India Gemini data
 */
router.get('/', validateAddress, async (req: Request, res: Response): Promise<void> => {
  const civicReq = req as CivicRequest;
  const address = civicReq.sanitizedAddress;
  const civicKey = process.env.CIVIC_API_KEY;
  const geocodingKey = process.env.GEOCODING_API_KEY ?? civicKey;
  const geminiKey = process.env.GEMINI_API_KEY;

  if (!civicKey) {
    console.error('[Civic Route] CIVIC_API_KEY is not set in environment.');
    res.status(500).json({
      error: 'Server configuration error: Civic API key is missing. Check .env setup.',
    });
    return;
  }

  // ── Step 1: Geocode to detect country ─────────────────────────────────────
  if (geocodingKey) {
    const geoResult = await geocodeAddress(address, geocodingKey);

    if (geoResult && isInIndia(geoResult)) {
      // ── Step 2: India path — bypass Civic API, use Gemini ───────────────
      console.log(`[Civic Route] India address detected: "${address}" → Gemini ECI synthesis`);

      if (!geminiKey) {
        res.status(500).json({
          error: 'GEMINI_API_KEY is not configured. Cannot serve India election data.',
        });
        return;
      }

      try {
        const locationName =
          getComponent(geoResult, 'locality') ??
          getComponent(geoResult, 'administrative_area_level_2') ??
          address;
        const stateName =
          getComponent(geoResult, 'administrative_area_level_1') ?? '';

        const electionData = await fetchIndiaDataFromGemini(locationName, stateName, geminiKey);

        res.status(200).json({
          indiaFallback: true,
          electionData,
          coordinates: {
            lat: geoResult.geometry.location.lat,
            lng: geoResult.geometry.location.lng,
          },
          formattedAddress: geoResult.formatted_address,
        });
        return;
      } catch (indiaErr) {
        console.error('[Civic Route] Gemini India synthesis failed:', indiaErr);
        res.status(500).json({
          error: 'Failed to generate India election data. Please try again.',
        });
        return;
      }
    }
  }

  // ── Step 3: US path — standard Google Civic Information API ───────────────
  try {
    const voterInfoUrl = `${CIVIC_API_BASE}/voterinfo`;
    const voterInfoResponse = await axios.get(voterInfoUrl, {
      params: {
        key: civicKey,
        address,
        electionId: '2000',
      },
      timeout: 10_000,
    });

    res.status(200).json(voterInfoResponse.data);
  } catch (err: unknown) {
    if (axios.isAxiosError(err)) {
      const status = err.response?.status ?? 500;
      const message = err.response?.data?.error?.message ?? 'Civic API request failed';

      if (status === 404) {
        try {
          const electionsUrl = `${CIVIC_API_BASE}/elections`;
          const electionsResponse = await axios.get(electionsUrl, {
            params: { key: civicKey },
            timeout: 10_000,
          });
          res.status(200).json({
            fallback: true,
            elections: electionsResponse.data.elections ?? [],
          });
          return;
        } catch (fallbackErr) {
          console.error('[Civic Route] Fallback elections fetch failed:', fallbackErr);
        }
      }

      console.error(`[Civic Route] Civic API error ${status}: ${message}`);
      res.status(status).json({ error: message });
    } else {
      console.error('[Civic Route] Unexpected error:', err);
      res.status(500).json({ error: 'An unexpected error occurred.' });
    }
  }
});

export default router;
