import { Router, Request, Response } from 'express';
import axios from 'axios';
import { validateAddress } from '../middleware/validate';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { stripGeminiJson } from '../utils/stripGeminiJson';

const router = Router();

/** Base URL for the Google Civic Information API */
const CIVIC_API_BASE = 'https://www.googleapis.com/civicinfo/v2';

/**
 * Typed request with the sanitized address attached by the validation middleware.
 */
type CivicRequest = Request & { sanitizedAddress: string };

// ── Geocoding Types ───────────────────────────────────────────────────────────

/** A single address component from the Google Geocoding API */
interface GeoAddressComponent {
  long_name: string;
  short_name: string;
  types: string[];
}

/** A single result entry from the Google Geocoding API */
interface GeoResult {
  address_components: GeoAddressComponent[];
  formatted_address: string;
  geometry: {
    location: { lat: number; lng: number };
  };
}

/** The full response from the Google Geocoding API */
interface GeoApiResponse {
  status: string;
  results: GeoResult[];
}

// ── India Election Data Types ─────────────────────────────────────────────────

/**
 * Structured election data generated by Gemini for an Indian constituency.
 * All fields are optional to tolerate model variability.
 */
interface IndiaElectionData {
  constituency?: string;
  state?: string;
  electionType?: string;
  expectedElectionYear?: string | number;
  voterRegistrationSteps?: string[];
  electionProcessSummary?: string;
  phases?: {
    authorization?: string;
    intelligence?: string;
    logistics?: string;
    execution?: string;
  };
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/**
 * Geocodes an address and returns the first result, or null if not found.
 * Uses the Google Maps Geocoding API.
 *
 * @param address - The address string to geocode
 * @param apiKey - Google Maps / Geocoding API key
 * @returns The first GeoResult, or null
 */
async function geocodeAddress(address: string, apiKey: string): Promise<GeoResult | null> {
  try {
    const url = `https://maps.googleapis.com/maps/api/geocode/json?address=${encodeURIComponent(address)}&key=${apiKey}`;
    const response = await fetch(url, { signal: AbortSignal.timeout(6_000) });
    if (!response.ok) return null;
    const data = await response.json() as GeoApiResponse;
    if (data.status !== 'OK' || data.results.length === 0) return null;
    return data.results[0];
  } catch {
    return null;
  }
}

/**
 * Checks whether a geocoding result is located in India by examining
 * the `country` address component for the short name "IN".
 *
 * @param result - A GeoResult from the Geocoding API
 * @returns true if the country code is "IN"
 */
function isInIndia(result: GeoResult): boolean {
  return result.address_components.some(
    (c) => c.types.includes('country') && c.short_name === 'IN'
  );
}

/**
 * Extracts a specific address component by type from a GeoResult.
 *
 * @param result - A GeoResult object
 * @param type - The component type to look for (e.g. 'locality')
 * @returns The long name of the matching component, or undefined
 */
function getComponent(result: GeoResult, type: string): string | undefined {
  return result.address_components.find((c) => c.types.includes(type))?.long_name;
}

/**
 * Builds the structured Gemini prompt for Indian constituency data.
 *
 * Handles granular input at any administrative level:
 * - City/town (e.g. "Bhubaneswar")
 * - District (e.g. "Koraput district, Odisha")
 * - Taluk/block/tehsil (e.g. "Puri Sadar block")
 * - Locality/neighbourhood (e.g. "Dharavi, Mumbai")
 *
 * Gemini is instructed to resolve the input to the correct
 * Lok Sabha + Vidhan Sabha constituency regardless of granularity.
 *
 * @param location - City, district, block, or locality name
 * @param state - State name (may be empty for city-only inputs)
 * @returns A detailed Gemini prompt string
 */
function buildIndiaPrompt(location: string, state: string): string {
  return `You are an expert on the Indian electoral system, the Election Commission of India (ECI), and Indian administrative geography.

A voter is located at: "${location}${state ? `, ${state}` : ''}, India"

This input may be a city, district, taluk, block, tehsil, ward, or neighbourhood. Resolve it to the correct electoral constituencies.

Generate a JSON object with EXACTLY this structure — no extra text, markdown, or code fences:
{
  "resolvedLocation": "<The most specific administrative unit you can identify, e.g. 'Koraput District, Odisha' or 'Dharavi Ward, K-East Zone, Mumbai'>",
  "district": "<Revenue district name, e.g. 'Koraput' or 'Mumbai City'>",
  "constituency": "<Vidhan Sabha (State Assembly) constituency name for this location>",
  "lokSabhaConstituency": "<Lok Sabha (Parliamentary) constituency that covers this location>",
  "state": "<State/UT name>",
  "electionType": "<'Lok Sabha' or 'State Assembly (Vidhan Sabha)' — whichever is most imminent as of 2025-2026>",
  "expectedElectionYear": "<year as a string, e.g. '2029'>",
  "voterRegistrationSteps": [
    "<Step 1: How to check voter ID eligibility at this location>",
    "<Step 2: How to register on voters.eci.gov.in or via Form 6>",
    "<Step 3: How to find the Booth Level Officer (BLO) for this constituency>",
    "<Step 4: How to download or verify the Voter ID / EPIC card>"
  ],
  "electionProcessSummary": "<2-3 sentence summary of the election process specific to this constituency and district>",
  "phases": {
    "authorization": "<How voter ID (EPIC card / Aadhaar-linked) registration works at this specific district/block level, including any local BLO office details if known>",
    "intelligence": "<How to research the specific candidates, sitting MLA/MP, and major political parties active in this constituency>",
    "logistics": "<How to find the exact polling booth for this ward/village, how EVMs + VVPATs work, and what documents to carry on polling day>",
    "execution": "<Step-by-step process of casting a vote on election day at a polling booth in this constituency>"
  }
}`;
}


/**
 * Calls the Gemini API to generate structured election data for an Indian location.
 * Strips any accidental markdown code fences from the model output.
 *
 * @param location - City or locality
 * @param state - State
 * @param geminiKey - GEMINI_API_KEY from process.env
 * @returns Parsed IndiaElectionData, or throws on parse failure
 */
async function fetchIndiaDataFromGemini(
  location: string,
  state: string,
  geminiKey: string
): Promise<IndiaElectionData> {
  const genAI = new GoogleGenerativeAI(geminiKey);
  const model = genAI.getGenerativeModel({
    model: 'gemini-1.5-flash',
    safetySettings: [
      { category: 'HARM_CATEGORY_HARASSMENT' as any, threshold: 'BLOCK_NONE' as any },
      { category: 'HARM_CATEGORY_HATE_SPEECH' as any, threshold: 'BLOCK_NONE' as any },
      { category: 'HARM_CATEGORY_SEXUALLY_EXPLICIT' as any, threshold: 'BLOCK_NONE' as any },
      { category: 'HARM_CATEGORY_DANGEROUS_CONTENT' as any, threshold: 'BLOCK_NONE' as any },
    ],
  });
  const prompt = buildIndiaPrompt(location, state);
  const result = await model.generateContent(prompt);
  const rawText = result.response.text();

  // Strip any markdown code fences Gemini may add despite being asked not to
  const jsonText = stripGeminiJson(rawText);
  console.log(`[Civic Route] Gemini raw (${rawText.length} chars) → stripped (${jsonText.length} chars)`);

  return JSON.parse(jsonText) as IndiaElectionData;
}

// ── India keyword fail-safe ────────────────────────────────────────────────────

/**
 * INDIA_KEYWORD_PATTERN
 *
 * Regex matching well-known Indian states, cities, or "India" / "IN".
 *
 * This is the **synchronous fail-safe** that fires BEFORE any API call is made.
 * It guarantees Indian addresses can never accidentally reach the US Civic API
 * even when the Geocoding key is missing or returns an unexpected result.
 */
const INDIA_KEYWORD_PATTERN =
  /\b(india|odisha|bhubaneswar|delhi|new\s+delhi|mumbai|bombay|bangalore|bengaluru|hyderabad|chennai|madras|kolkata|calcutta|pune|ahmedabad|jaipur|lucknow|kanpur|nagpur|patna|indore|thane|bhopal|visakhapatnam|surat|vadodara|ludhiana|agra|nashik|faridabad|meerut|rajkot|maharashtra|karnataka|tamil\s+nadu|west\s+bengal|gujarat|rajasthan|uttar\s+pradesh|bihar|madhya\s+pradesh|andhra\s+pradesh|telangana|kerala|punjab|haryana|assam|jharkhand|uttarakhand|chhattisgarh|jammu|kashmir|goa|manipur|meghalaya|mizoram|nagaland|sikkim|tripura|arunachal)\b/i;

/**
 * Returns true if the address string matches any known Indian keyword.
 * Case-insensitive. Checks whole words only (word boundary anchors).
 *
 * @param address - The sanitized address string
 * @returns true if the address is recognisably Indian
 */
function isIndianKeyword(address: string): boolean {
  return INDIA_KEYWORD_PATTERN.test(address);
}

/**
 * Shared response helper: runs Gemini ECI synthesis and sends the
 * IndiaApiResponse JSON. Called from both Layer 1 and Layer 2.
 *
 * @param res - Express response object
 * @param geminiKey - GEMINI_API_KEY
 * @param locationName - Resolved city/locality (or raw address as fallback)
 * @param stateName - Resolved state name (may be empty string)
 * @param coordinates - Geocoded lat/lng or null when geocoding was skipped
 * @param formattedAddress - Geocoded formatted address or raw input
 */
async function sendIndiaGeminiResponse(
  res: Response,
  geminiKey: string,
  locationName: string,
  stateName: string,
  coordinates: { lat: number; lng: number } | null,
  formattedAddress: string
): Promise<void> {
  console.log(
    `[Civic Route] ► GEMINI PATH — location="${locationName}", state="${stateName}", coords=${coordinates ? JSON.stringify(coordinates) : 'none'}`
  );

  const electionData = await fetchIndiaDataFromGemini(locationName, stateName, geminiKey);

  res.status(200).json({
    indiaFallback: true,
    electionData,
    coordinates,
    formattedAddress,
  });
}

// ── Route ─────────────────────────────────────────────────────────────────────

/**
 * GET /api/civic
 *
 * Bulletproof address resolver with three-layer India detection:
 *
 * **LAYER 1 — Synchronous keyword pre-check (zero API calls):**
 *   If the address contains any known Indian city/state name or "India",
 *   immediately route to the Gemini ECI synthesis engine.
 *   Guarantees Indian addresses NEVER reach the US Civic API.
 *
 * **LAYER 2 — Geocoding API country check (async, authoritative):**
 *   For addresses that passed Layer 1, geocode and check country_code = "IN".
 *   If India is confirmed, route to Gemini with precise geocoded location.
 *
 * **LAYER 3 — US Google Civic Information API:**
 *   Only reached when both Layer 1 and Layer 2 confirmed a non-India address.
 *
 * All decision points emit console.log() for Cloud Run log visibility.
 *
 * @query address - The voter's address string (validated by middleware)
 * @returns CivicVoterInfo, fallback elections list, or IndiaApiResponse
 */
router.get('/', validateAddress, async (req: Request, res: Response): Promise<void> => {
  const civicReq = req as CivicRequest;
  const address = civicReq.sanitizedAddress;
  const civicKey = process.env.CIVIC_API_KEY;
  const geocodingKey = process.env.GEOCODING_API_KEY ?? civicKey;
  const geminiKey = process.env.GEMINI_API_KEY;

  // ── Audit log: always show the raw input ──────────────────────────────────
  console.log(`[Civic Route] ► Incoming address: "${address}"`);

  if (!civicKey) {
    console.error('[Civic Route] ✗ CIVIC_API_KEY is not set in environment.');
    res.status(500).json({
      error: 'Server configuration error: Civic API key is missing. Check .env setup.',
    });
    return;
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // LAYER 1: Synchronous keyword pre-check — zero latency, zero API calls
  // ═══════════════════════════════════════════════════════════════════════════
  if (isIndianKeyword(address)) {
    console.log(
      `[Civic Route] ► LAYER 1 HIT (keyword): "${address}" → INDIA path. Geocoding + Civic APIs skipped.`
    );

    if (!geminiKey) {
      console.error('[Civic Route] ✗ GEMINI_API_KEY missing — cannot serve India data.');
      res.status(500).json({
        error: 'GEMINI_API_KEY is not configured. Cannot serve India election data.',
      });
      return;
    }

    // Best-effort geocoding for lat/lng enrichment (does not block the path)
    let locationName = address;
    let stateName = '';
    let coordinates: { lat: number; lng: number } | null = null;
    let formattedAddress = address;

    if (geocodingKey) {
      const geoResult = await geocodeAddress(address, geocodingKey);
      if (geoResult) {
        coordinates = {
          lat: geoResult.geometry.location.lat,
          lng: geoResult.geometry.location.lng,
        };
        formattedAddress = geoResult.formatted_address;
        locationName =
          getComponent(geoResult, 'locality') ??
          getComponent(geoResult, 'administrative_area_level_2') ??
          address;
        stateName = getComponent(geoResult, 'administrative_area_level_1') ?? '';
        console.log(
          `[Civic Route] ► Layer 1 geocode enrichment: "${locationName}", "${stateName}", ${JSON.stringify(coordinates)}`
        );
      } else {
        console.warn(
          `[Civic Route] ⚠ Layer 1 geocoding returned no result for "${address}" — using raw address for Gemini prompt.`
        );
      }
    }

    try {
      await sendIndiaGeminiResponse(res, geminiKey, locationName, stateName, coordinates, formattedAddress);
    } catch (indiaErr) {
      console.error('[Civic Route] ✗ Gemini synthesis failed (Layer 1):', indiaErr);
      res.status(500).json({ error: 'Failed to generate India election data. Please try again.' });
    }
    return;
  }

  console.log(`[Civic Route] ► LAYER 1 MISS (no India keyword). Proceeding to Geocoding API.`);

  // ═══════════════════════════════════════════════════════════════════════════
  // LAYER 2: Geocoding API country check
  // ═══════════════════════════════════════════════════════════════════════════
  if (geocodingKey) {
    const geoResult = await geocodeAddress(address, geocodingKey);

    if (geoResult) {
      const countryCode =
        geoResult.address_components.find((c) => c.types.includes('country'))?.short_name ??
        'unknown';
      console.log(
        `[Civic Route] ► Geocoded: "${geoResult.formatted_address}" — country_code="${countryCode}"`
      );

      if (isInIndia(geoResult)) {
        console.log(
          `[Civic Route] ► LAYER 2 HIT (geocode): country_code=IN for "${address}" → INDIA path.`
        );

        if (!geminiKey) {
          res.status(500).json({
            error: 'GEMINI_API_KEY is not configured. Cannot serve India election data.',
          });
          return;
        }

        const locationName =
          getComponent(geoResult, 'locality') ??
          getComponent(geoResult, 'administrative_area_level_2') ??
          address;
        const stateName = getComponent(geoResult, 'administrative_area_level_1') ?? '';
        const coordinates = {
          lat: geoResult.geometry.location.lat,
          lng: geoResult.geometry.location.lng,
        };

        try {
          await sendIndiaGeminiResponse(res, geminiKey, locationName, stateName, coordinates, geoResult.formatted_address);
        } catch (indiaErr) {
          console.error('[Civic Route] ✗ Gemini synthesis failed (Layer 2):', indiaErr);
          res.status(500).json({ error: 'Failed to generate India election data. Please try again.' });
        }
        return;
      }

      console.log(`[Civic Route] ► LAYER 2 MISS (country_code="${countryCode}"). Proceeding to US Civic API.`);
    } else {
      console.warn(`[Civic Route] ⚠ Geocoding returned no result for "${address}" — proceeding to US Civic API.`);
    }
  } else {
    console.warn(`[Civic Route] ⚠ No geocoding key available — skipping Layer 2.`);
  }

  // ═══════════════════════════════════════════════════════════════════════════
  // LAYER 3: US Google Civic Information API
  // ═══════════════════════════════════════════════════════════════════════════
  console.log(`[Civic Route] ► LAYER 3: US Civic API for "${address}".`);

  try {
    const voterInfoUrl = `${CIVIC_API_BASE}/voterinfo`;
    const voterInfoResponse = await axios.get(voterInfoUrl, {
      params: { key: civicKey, address, electionId: '2000' },
      timeout: 10_000,
    });

    console.log(`[Civic Route] ✓ US Civic API success for "${address}".`);
    res.status(200).json(voterInfoResponse.data);
  } catch (err: unknown) {
    if (axios.isAxiosError(err)) {
      const status = err.response?.status ?? 500;
      const message = err.response?.data?.error?.message ?? 'Civic API request failed';

      if (status === 404) {
        try {
          const electionsUrl = `${CIVIC_API_BASE}/elections`;
          const electionsResponse = await axios.get(electionsUrl, {
            params: { key: civicKey },
            timeout: 10_000,
          });
          console.log(`[Civic Route] ✓ Returning elections fallback list for "${address}".`);
          res.status(200).json({
            fallback: true,
            elections: electionsResponse.data.elections ?? [],
          });
          return;
        } catch (fallbackErr) {
          console.error('[Civic Route] ✗ Fallback elections fetch failed:', fallbackErr);
        }
      }

      console.error(`[Civic Route] ✗ Civic API error ${status}: ${message}`);
      res.status(status).json({ error: message });
    } else {
      console.error('[Civic Route] ✗ Unexpected error:', err);
      res.status(500).json({ error: 'An unexpected error occurred.' });
    }
  }
});

export default router;
