/**
 * useCivicData.ts
 *
 * Custom React hook for fetching election data.
 *
 * Features:
 * - Tries the US Google Civic Information API first via /api/civic
 * - If the address resolves to India, automatically falls back to the
 *   /api/india Gemini-powered International Fallback Engine
 * - Maps the India response into the standard CivicVoterInfo shape so
 *   all downstream components (ElectionPage, RoadmapStepper, PollingMap)
 *   render identically regardless of data source
 * - 24-hour localStorage caching via cache.ts
 * - Abort controller to cancel stale requests on unmount
 * - Typed return value with loading and error states
 */
import { useState, useEffect, useCallback, useRef } from 'react';
import type { CivicApiResponse, CivicVoterInfo, IndiaApiResponse } from '../types';
import { isIndiaFallback } from '../types';
import { cacheGet, cacheSet, civicCacheKey } from '@shared/utils/cache';
import { mapIndiaToCivicVoterInfo } from '../utils/indiaMapper';

/** Internal state shape for the hook */
interface UseCivicDataState {
  /** The API response data, if available */
  data: CivicApiResponse | null;
  /** True while a network request is in flight */
  loading: boolean;
  /** Error message if the request failed */
  error: string | null;
  /** True if this data came from the cache */
  fromCache: boolean;
  /** True if this data was generated by the Gemini India fallback engine */
  isIndiaMode: boolean;
}

/** Public return type of useCivicData */
interface UseCivicDataResult extends UseCivicDataState {
  /** Call to re-fetch, bypassing the cache */
  refetch: () => void;
}

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? '';

/**
 * Detects whether an address string is likely located in India by checking
 * for India-specific keywords. Used as a fast pre-check before API calls.
 *
 * @param address - The raw address string from the user
 * @returns true if the address contains India-specific location hints
 */
function looksLikeIndia(address: string): boolean {
  const lower = address.toLowerCase();
  // Match common Indian state names, union territories, and the word "india"
  const indiaKeywords = [
    'india', 'bhubaneswar', 'odisha', 'delhi', 'mumbai', 'bangalore', 'bengaluru',
    'hyderabad', 'chennai', 'kolkata', 'calcutta', 'pune', 'ahmedabad', 'jaipur',
    'lucknow', 'kanpur', 'nagpur', 'patna', 'indore', 'thane', 'bhopal', 'visakhapatnam',
    'pimpri', 'vadodara', 'ludhiana', 'agra', 'nashik', 'faridabad', 'meerut', 'rajkot',
    'maharashtra', 'karnataka', 'tamil nadu', 'west bengal', 'gujarat', 'rajasthan',
    'uttar pradesh', 'bihar', 'madhya pradesh', 'andhra pradesh', 'telangana',
    'kerala', 'punjab', 'haryana', 'assam', 'jharkhand', 'uttarakhand', 'chhattisgarh',
    'jammu', 'kashmir', 'goa', 'manipur', 'meghalaya', 'mizoram', 'nagaland',
    'sikkim', 'tripura', 'arunachal',
  ];
  return indiaKeywords.some((kw) => lower.includes(kw));
}

/**
 * Calls the /api/india backend endpoint and returns the response.
 *
 * @param address - The user's address string
 * @param signal - AbortController signal for cancellation
 * @returns IndiaApiResponse from the backend
 * @throws Error if the request fails or is aborted
 */
async function fetchIndiaData(address: string, signal: AbortSignal): Promise<IndiaApiResponse> {
  const res = await fetch(`${API_BASE}/api/india`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ address }),
    signal,
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({ error: `HTTP ${res.status}` })) as { error?: string };
    throw new Error(err.error ?? `HTTP ${res.status}`);
  }
  return res.json() as Promise<IndiaApiResponse>;
}

/**
 * Fetches civic election data for the given address.
 *
 * First checks the US Civic API. If that fails or if the address is
 * detected to be in India, the hook transparently falls back to the
 * Gemini-powered /api/india endpoint. The returned `data` object is always
 * a valid CivicVoterInfo so all downstream components require no changes.
 *
 * @param address - The voter's address string (pre-sanitized)
 * @returns State object with data, loading, error, fromCache, isIndiaMode, and refetch
 *
 * @example
 * const { data, loading, error, isIndiaMode } = useCivicData('Bhubaneswar, Odisha');
 */
export function useCivicData(address: string | null): UseCivicDataResult {
  const [state, setState] = useState<UseCivicDataState>({
    data: null,
    loading: false,
    error: null,
    fromCache: false,
    isIndiaMode: false,
  });

  // Track fetch version to ignore stale responses
  const fetchVersion = useRef(0);

  const fetchData = useCallback(
    async (bypassCache = false) => {
      if (!address || address.trim().length === 0) {
        return;
      }

      const cacheKey = civicCacheKey(address);

      // Check cache first (unless bypassCache is set)
      if (!bypassCache) {
        const cached = cacheGet<CivicApiResponse>(cacheKey);
        if (cached) {
          setState({
            data: cached,
            loading: false,
            error: null,
            fromCache: true,
            isIndiaMode: false,
          });
          return;
        }
      }

      const currentVersion = ++fetchVersion.current;
      setState((prev) => ({ ...prev, loading: true, error: null, fromCache: false }));

      const controller = new AbortController();

      try {
        // ── Fast pre-check: does the address look like India? ──────────────
        if (looksLikeIndia(address)) {
          const indiaData = await fetchIndiaData(address.trim(), controller.signal);

          if (currentVersion !== fetchVersion.current) return;

          if (isIndiaFallback(indiaData)) {
            // Map to CivicVoterInfo so UI components work unchanged
            const mapped: CivicVoterInfo = mapIndiaToCivicVoterInfo(indiaData);
            cacheSet(cacheKey, mapped);
            setState({
              data: mapped,
              loading: false,
              error: null,
              fromCache: false,
              isIndiaMode: true,
            });
            return;
          }
        }

        // ── Default: try the US Civic API ──────────────────────────────────
        const url = `${API_BASE}/api/civic?address=${encodeURIComponent(address)}`;
        const response = await fetch(url, { signal: controller.signal });

        if (currentVersion !== fetchVersion.current) return;

        if (!response.ok) {
          const errorData = await response.json().catch(() => ({})) as { error?: string };
          throw new Error(errorData.error ?? `HTTP ${response.status}`);
        }

        const data = await response.json() as CivicApiResponse;
        cacheSet(cacheKey, data);

        setState({ data, loading: false, error: null, fromCache: false, isIndiaMode: false });
      } catch (err: unknown) {
        if (err instanceof Error && err.name === 'AbortError') return;

        const message = err instanceof Error ? err.message : 'Unknown error';

        // ── Final fallback: if Civic API error might be an India address ───
        // This catches cases where looksLikeIndia() missed it but the Civic
        // API returned a 403/404 (no US data).
        if (
          message.includes('No data') ||
          message.includes('403') ||
          message.includes('404') ||
          message.includes('400')
        ) {
          try {
            const indiaData = await fetchIndiaData(address.trim(), controller.signal);
            if (isIndiaFallback(indiaData)) {
              const mapped: CivicVoterInfo = mapIndiaToCivicVoterInfo(indiaData);
              cacheSet(cacheKey, mapped);
              setState({
                data: mapped,
                loading: false,
                error: null,
                fromCache: false,
                isIndiaMode: true,
              });
              return;
            }
          } catch {
            // India fallback also failed — fall through to show the original error
          }
        }

        setState((prev) => ({
          ...prev,
          loading: false,
          error: `Failed to fetch civic data: ${message}`,
        }));
      }

      return () => controller.abort();
    },
    [address]
  );

  useEffect(() => {
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void fetchData();
  }, [fetchData]);

  const refetch = useCallback(() => {
    void fetchData(true);
  }, [fetchData]);

  return { ...state, refetch };
}
