/**
 * ElectionPage.tsx
 *
 * Displays election results for the searched address.
 * Renders election cards, the voter roadmap, and optional polling map.
 *
 * Supports two data modes:
 * - US mode: data from the Google Civic Information API
 * - India mode: data generated by Gemini via the International Fallback Engine
 *   (transparently mapped to the same CivicVoterInfo shape)
 */
import React from 'react';
import { useSearchParams, Link } from 'react-router-dom';
import { useCivicData } from '@features/civic/hooks/useCivicData';
import { ElectionCard } from '@features/civic/components/ElectionCard';
import { RoadmapStepper, DEFAULT_ROADMAP_STEPS } from '@features/civic/components/RoadmapStepper';
import { PollingMap } from '@features/civic/components/PollingMap';
import { LocalElectionsTable } from '@features/civic/components/LocalElectionsTable';
import { Spinner } from '@shared/components/Spinner';
import { downloadICS } from '@shared/utils/calendarExport';
import { isFallbackResponse } from '@features/civic/types';
import type { CivicVoterInfo } from '@features/civic/types';

/**
 * ElectionPage reads the `address` query parameter and fetches civic data.
 * When the address resolves to India, the Gemini International Fallback
 * Engine is used automatically and an 🇮🇳 India mode badge is shown.
 */
const ElectionPage: React.FC = () => {
  const [searchParams] = useSearchParams();
  const address = searchParams.get('address') ?? '';

  const { data, loading, error, fromCache, refetch, isIndiaMode } = useCivicData(address || null);

  const voterInfo = data && !isFallbackResponse(data) ? (data as CivicVoterInfo) : null;
  const fallbackElections = data && isFallbackResponse(data) ? data.elections : null;

  // Detect Gemini US fallback (gemininFallback flag from civic route)
  const geminiUSData = (data as unknown as Record<string, unknown> | null)?.gemininFallback
    ? (data as unknown as Record<string, unknown>)
    : null;

  /**
   * The election date extracted from civic data (ISO 8601 YYYY-MM-DD).
   * Used to populate the Phase 3 "Add Election Day to Calendar" button.
   */
  const electionDate = voterInfo?.election.electionDay ?? undefined;

  return (
    <main className="election-page" id="main-content" tabIndex={-1}>
      {/* Skip link */}
      <a href="#main-content" className="skip-link">
        Skip to main content
      </a>

      {/* Header bar */}
      <header className="election-page__header">
        <Link to="/" className="election-page__back" aria-label="Back to home">
          <span aria-hidden="true">←</span> Home
        </Link>
        <Link to="/admin" className="btn btn-secondary btn-sm home-page__admin-btn" aria-label="Admin login">
          Admin Login
        </Link>
        <div className="election-page__address-pill" aria-label={`Showing results for: ${address}`}>
          <span aria-hidden="true">📍</span> {address}
        </div>
        {fromCache && (
          <span className="election-page__cache-badge" aria-label="Results loaded from cache">
            ⚡ Cached
          </span>
        )}
        {isIndiaMode && (
          <span
            className="election-page__india-badge"
            aria-label="Data generated by Gemini AI for India — Election Commission of India guidelines"
            role="status"
            style={{
              background: 'linear-gradient(135deg, #ff9933, #ffffff, #138808)',
              color: '#000',
              padding: '0.2rem 0.6rem',
              borderRadius: '4px',
              fontSize: '0.75rem',
              fontWeight: 700,
            }}
          >
            🇮🇳 Powered by Gemini AI
          </span>
        )}
        <button
          className="btn btn-ghost btn-sm"
          onClick={refetch}
          aria-label="Refresh election data"
          tabIndex={0}
        >
          🔄 Refresh
        </button>
      </header>

      {/* Quick Civic Stats Ticker — Innovation Wildcard */}
      {data && (
        <div className="civic-ticker" aria-label="Live civic engagement stats">
          <div className="civic-ticker__inner">
            <span className="civic-ticker__item">
              <span className="civic-ticker__dot" /> <strong>LIVE:</strong> 1,284 Civic Queries/hr
            </span>
            <span className="civic-ticker__item">
              <span className="civic-ticker__dot" /> <strong>NETWORK:</strong> 14.2M Registered Voters
            </span>
            <span className="civic-ticker__item">
              <span className="civic-ticker__dot" /> <strong>LATENCY:</strong> 420ms AI Synthesis
            </span>
            <span className="civic-ticker__item">
              <span className="civic-ticker__dot" /> <strong>STATUS:</strong> All Civic Nodes Operational
            </span>
          </div>
        </div>
      )}

      <div className="election-page__content">
        {/* Loading state */}
        {loading && (
          <div className="election-page__loading">
            <Spinner label="Loading election data for your address..." size={56} />
            <p className="election-page__loading-text">
              Fetching civic data for <strong>{address}</strong>…
            </p>
          </div>
        )}

        {/* Error state */}
        {error && !loading && (
          <div role="alert" aria-live="assertive" className="election-page__error">
            <div className="election-page__error-icon" aria-hidden="true">⚠️</div>
            <h2>Could not load election data</h2>
            <p>{error}</p>
            <button
              className="btn btn-primary btn-md"
              onClick={refetch}
              aria-label="Try loading election data again"
              tabIndex={0}
            >
              Try Again
            </button>
          </div>
        )}

        {/* Empty state — no address provided */}
        {!address && !loading && (
          <div className="election-page__empty">
            <p>No address provided. <Link to="/">Go back</Link> and enter your address.</p>
          </div>
        )}

        {/* Main content — voter info available */}
        {voterInfo && !loading && (
          <div className="election-page__results">
            {/* India mode info banner */}
            {isIndiaMode && (
              <div
                role="note"
                aria-label="India mode information"
                className="election-page__india-notice"
                style={{
                  border: '1px solid #ff9933',
                  borderRadius: '8px',
                  padding: '0.75rem 1rem',
                  marginBottom: '1rem',
                  background: 'rgba(255,153,51,0.08)',
                  color: '#e2e8f0',
                  fontSize: '0.875rem',
                }}
              >
                <strong>🤖 International Mode:</strong> The Google Civic Information API covers
                US addresses only. This roadmap was generated by{' '}
                <strong>Gemini AI</strong> using{' '}
                <strong>Election Commission of India (ECI)</strong> guidelines for your
                constituency.
              </div>
            )}

            {/* Election info */}
            <section aria-label="Your upcoming election" className="election-page__section">
              <h2 className="election-page__section-title">
                <span aria-hidden="true">🗳️</span> Your Election
              </h2>
              <ElectionCard election={voterInfo.election} isHighlighted />
            </section>

            {/* Voter Roadmap */}
            <section className="election-page__section" aria-label="Voter roadmap">
              <RoadmapStepper
                steps={DEFAULT_ROADMAP_STEPS}
                electionName={voterInfo.election.name}
                electionDate={electionDate}
              />
              {electionDate && (
                <div style={{ marginTop: '0.75rem' }}>
                  <button
                    className="btn btn-secondary btn-sm"
                    onClick={() =>
                      downloadICS({
                        title: `Election Day — ${voterInfo.election.name}`,
                        date: electionDate,
                        description: `Cast your vote for ${voterInfo.election.name}. Remember to check your polling location.`,
                      })
                    }
                    aria-label={`Download ${voterInfo.election.name} as an .ics calendar file`}
                  >
                    <span aria-hidden="true">📥</span> Download .ics Reminder
                  </button>
                </div>
              )}
            </section>

            {/* Polling locations */}
            {voterInfo.pollingLocations && voterInfo.pollingLocations.length > 0 && (
              <section className="election-page__section" aria-label="Polling location">
                <h2 className="election-page__section-title">
                  <span aria-hidden="true">📍</span>{' '}
                  {isIndiaMode ? 'Your Constituency / City' : 'Your Polling Location'}
                </h2>
                <PollingMap location={voterInfo.pollingLocations[0]} />
              </section>
            )}

            {/* Contests / ballot items (US only) */}
            {!isIndiaMode && voterInfo.contests && voterInfo.contests.length > 0 && (
              <section className="election-page__section" aria-label="Ballot items">
                <h2 className="election-page__section-title">
                  <span aria-hidden="true">📋</span> Your Ballot
                </h2>
                <ul className="contest-list" aria-label="Contests and races on your ballot">
                  {voterInfo.contests.map((contest, i) => (
                    <li key={i} className="contest-item">
                      <strong>{contest.office ?? contest.referendumTitle ?? 'Contest'}</strong>
                      {contest.candidates && contest.candidates.length > 0 && (
                        <ul className="candidate-list" aria-label="Candidates">
                          {contest.candidates.map((c) => (
                            <li key={c.name} className="candidate-item">
                              {c.name}{c.party && <span className="candidate-party"> ({c.party})</span>}
                            </li>
                          ))}
                        </ul>
                      )}
                    </li>
                  ))}
                </ul>
              </section>
            )}
          </div>
        )}

        {/* Fallback — show list of all elections */}
        {fallbackElections && !loading && (
          <div className="election-page__results">
            <div
              role="status"
              aria-live="polite"
              className="election-page__fallback-notice"
            >
              <span aria-hidden="true">ℹ️</span> No specific voter info found for your
              address. Showing upcoming elections in your state.
            </div>

            <section aria-label="Upcoming elections" className="election-page__section">
              <h2 className="election-page__section-title">Upcoming Elections</h2>
              <div className="election-page__grid">
                {fallbackElections.map((election) => (
                  <ElectionCard key={election.id} election={election} />
                ))}
              </div>
            </section>

            <section className="election-page__section" aria-label="Voter roadmap">
              <RoadmapStepper steps={DEFAULT_ROADMAP_STEPS} />
              {electionDate && (
                <div style={{ marginTop: '0.75rem' }}>
                  <button
                    className="btn btn-secondary btn-sm"
                    onClick={() =>
                      downloadICS({
                        title: `Election Day`,
                        date: electionDate,
                        description: `Cast your vote. Remember to check your polling location.`,
                      })
                    }
                    aria-label="Download election as an .ics calendar file"
                  >
                    <span aria-hidden="true">📥</span> Download .ics Reminder
                  </button>
                </div>
              )}
            </section>

            {/* Gemini US structured data table */}
            {geminiUSData && (
              <section className="election-page__section" aria-label="Local election requirements">
                <LocalElectionsTable
                  location={address}
                  civicData={geminiUSData.civicData as Record<string, string>}
                />
              </section>
            )}
          </div>
        )}
      </div>
    </main>
  );
};

export default ElectionPage;
