/**
 * Civic data type definitions.
 *
 * These types mirror the Google Civic Information API v2 response shapes.
 * https://developers.google.com/civic-information/docs/v2/voterInfo/query
 */

/** A single election from the Civic API */
export interface CivicElection {
  id: string;
  name: string;
  /** ISO 8601 date string, e.g. "2024-11-05" */
  electionDay: string;
  ocdDivisionId: string;
}

/** A polling location from the Civic API */
export interface PollingLocation {
  address: {
    locationName?: string;
    line1?: string;
    city?: string;
    state?: string;
    zip?: string;
  };
  notes?: string;
  pollingHours?: string;
  name?: string;
  startDate?: string;
  endDate?: string;
  latitude?: number;
  longitude?: number;
}

/** A contest/race on the ballot */
export interface Contest {
  office?: string;
  type?: string;
  candidates?: Candidate[];
  referendumTitle?: string;
  referendumSubtitle?: string;
  referendumBallotResponses?: string[];
}

/** A candidate in a contest */
export interface Candidate {
  name: string;
  party?: string;
  candidateUrl?: string;
  photoUrl?: string;
}

/** The full voterInfoQuery response */
export interface CivicVoterInfo {
  election: CivicElection;
  normalizedInput?: {
    line1?: string;
    city?: string;
    state?: string;
    zip?: string;
  };
  pollingLocations?: PollingLocation[];
  earlyVoteSites?: PollingLocation[];
  dropOffLocations?: PollingLocation[];
  contests?: Contest[];
  mailOnly?: boolean;
}

/** Fallback response when voterInfo is unavailable */
export interface CivicFallbackResponse {
  fallback: true;
  elections: CivicElection[];
}

/** Union type for all possible civic API responses */
export type CivicApiResponse = CivicVoterInfo | CivicFallbackResponse;

/** Type guard: checks if a response is the fallback elections list */
export function isFallbackResponse(
  response: CivicApiResponse
): response is CivicFallbackResponse {
  return 'fallback' in response && response.fallback === true;
}

/** Roadmap step definitions */
export interface RoadmapStep {
  id: number;
  title: string;
  description: string;
  deadline?: string;
  isCompleted: boolean;
  isCurrent: boolean;
}

// ── India Fallback Engine Types ───────────────────────────────────────────────

/**
 * Structured election data for an Indian constituency, generated by Gemini.
 * All fields are optional to tolerate model variability.
 */
export interface IndiaElectionData {
  constituency?: string;
  state?: string;
  electionType?: string;
  expectedElectionYear?: string | number;
  voterRegistrationSteps?: string[];
  electionProcessSummary?: string;
  phases?: {
    authorization?: string;
    intelligence?: string;
    logistics?: string;
    execution?: string;
  };
}

/**
 * Full response returned by the /api/india backend route.
 * Contains the Gemini-generated election data plus geocoded coordinates.
 */
export interface IndiaApiResponse {
  indiaFallback: true;
  electionData: IndiaElectionData;
  coordinates: { lat: number; lng: number } | null;
  formattedAddress: string;
}

/**
 * Extended union type covering all possible API responses including India fallback.
 */
export type AnyApiResponse = CivicApiResponse | IndiaApiResponse;

/**
 * Type guard: checks if a response is the India Gemini fallback.
 *
 * @param response - Any API response object
 * @returns true if the response is an IndiaApiResponse
 */
export function isIndiaFallback(response: AnyApiResponse): response is IndiaApiResponse {
  return 'indiaFallback' in response && (response as IndiaApiResponse).indiaFallback === true;
}
